#!/bin/bash

# file: projectscript1.bash
# overview: a script that shows system information on a generated html page
# author: Samuel Barrows
# date: 09/28/20

#Style the page
style(){
    cat<<EOF
<style>
html{
  background-color: lemonchiffon;
  font-family: "courier"
}
</style>
EOF
}

#basic information
basic_info(){
    distro=$(cat /etc/lsb-release | grep "DESCRIPTION" | cut -d "=" -f 2)
    kernel=$(uname -r)
    cpu_arch=$(uname -i)
    cat <<EOF
        Distro: $distro<br>
        Kernel Version: $kernel<br>
        CPU Archetecture: $cpu_arch<br>
EOF
}

#free memory
free_memory(){
    #this cut filter will cut the shared and on fields
    memory=$(free -hm | cut -c 1-45 | while IFS= read -r line; do echo "$line<br>"; done)
    echo "<b>Free memory at the time of file generation:</b><br><br> $memory"
}

#Disk Info Function
disk_info(){
    disk_space=$(df -h | while IFS= read -r line; do echo "$line<br>"; done)
    echo "<b>Free disk space:</b><br> $disk_space"
}

#Generate a global list of users. This will be useful for a few functions
users=$(sudo cat /etc/passwd | grep bash | cut -d ":" -f 6 | sort | sed 's/home//' | tr -d '/')

#shell users on the system
shell_users(){
    for user in $users
    do
        echo "<b>$user</b> <br>"
        echo "$(id $user)<br><br>"
    done
}

#Network information
network_information(){
    network=$(ip addr show | grep inet | grep -v inet6 | grep -v 127.0.0.1 | tr -s " " | cut -d " " -f 3)
    echo "<b>Current IP Address:</b> $network"
}

#The title
title(){
    user=$(whoami)
    timerun=$(date)
    echo "This webpage was generated by <b>$user</b> at <b>$timerun</b>"
}

#Number of packages installed
numbered_packages(){
    package_num=$(dpkg -l | grep "ii" | wc -l)
    echo "Number of packages installed: <b>$package_num</b>"
}

#See a list of active processes on the machine per user
services(){
    #This will pull only the process name from the list
    service_list=$(for user in $users ; do echo "<br><b>$user</b><br>" ; ps -U $user -u $user | tr -s " " | cut -d " " -f 5 | grep -v "CMD" | while IFS= read -r line; do echo "$line<br>"; done; done)
    echo "Active services per <b>user</b>:<br><br> $service_list<br><br>"
}

#Check to make sure the script is being run as root
if [[ $(whoami | id -u) -ne 0 ]]
then
    >&2 echo "This script must be run as root!"
    exit;
fi

#The HTML page
cat <<EOF
  <html>
  $(style)
  <h1>Information about my Virtual Machine</h1>
  <p>$(title)</p>
  <h1>The Basics</h1>
  <p>$(basic_info)</p>
  <h1>It's Free Memory</h1>
  <p>$(free_memory)</p>
  <h1>Information About My Disks</h1>
  <p>$(disk_info)</p>
  <h1>Here are the users on the system!</h1>
  <p>$(shell_users)</p>
  <h1>Networking!</h1>
  <p>$(network_information)</p>
  <h1>Number of Packages on this machine</h1>
  <p>$(numbered_packages)</p>
  <h1>Running Services on the machine per users</h1>
  <p>$(services)</p>
  </html>
EOF
